version: '3.1'
services:
  php:
    build: .
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - 33061:3306